version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /public
        volumes:
            - '.:/public'
            - './dump/:/docker-entrypoint-initdb.d'
        environment:
            - MYSQL_ROOT_PASSWORD=123123
            - MYSQL_DATABASE=spa
            - MYSQL_USER=spa
            - MYSQL_PASSWORD=123123
        ports:
            - '3333:3306'
        container_name: spa_db

    webserver:
        image: 'nginx:alpine'
        working_dir: /public
        volumes:
            - '.:/public'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8889:80'
        container_name: spa_nginx

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /public
        volumes:
            - '.:/public'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
        container_name: spa_php
